"""empty message

Revision ID: c1a344b2b7c3
Revises: eaaa45baad99
Create Date: 2024-04-25 02:24:44.494121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a344b2b7c3'
down_revision: Union[str, None] = 'eaaa45baad99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Uslugi', sa.Column('cena', sa.Integer(), nullable=True))
    op.drop_column('Zayavki', 'cena')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Zayavki', sa.Column('cena', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Uslugi', 'cena')
    # ### end Alembic commands ###
