"""empty message

Revision ID: eaaa45baad99
Revises: 
Create Date: 2024-04-24 02:29:14.957195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaaa45baad99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Client',
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('full_name_cl', sa.String(length=250), nullable=False),
    sa.Column('telephone', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id_client')
    )
    op.create_table('Uslugi',
    sa.Column('id_uslugi', sa.Integer(), nullable=False),
    sa.Column('remont', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_uslugi')
    )
    op.create_table('Auto',
    sa.Column('number_auto', sa.String(length=7), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('marka', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['Client.id_client'], ),
    sa.PrimaryKeyConstraint('number_auto')
    )
    op.create_table('Zayavki',
    sa.Column('id_zayavki', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=20), nullable=False),
    sa.Column('cena', sa.Integer(), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['Client.id_client'], ),
    sa.PrimaryKeyConstraint('id_zayavki')
    )
    op.create_table('Rabotnik',
    sa.Column('id_uslugi', sa.Integer(), nullable=False),
    sa.Column('id_zayavki', sa.Integer(), nullable=False),
    sa.Column('full_name_rab', sa.String(length=250), nullable=False),
    sa.Column('post', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['id_uslugi'], ['Uslugi.id_uslugi'], ),
    sa.ForeignKeyConstraint(['id_zayavki'], ['Zayavki.id_zayavki'], ),
    sa.PrimaryKeyConstraint('id_uslugi', 'id_zayavki')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Rabotnik')
    op.drop_table('Zayavki')
    op.drop_table('Auto')
    op.drop_table('Uslugi')
    op.drop_table('Client')
    # ### end Alembic commands ###
